import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import firebase from '@/firebase/initFirebase.js';
import WriteToCloudFirestore from '@/components/cloudFirestore/Write.js';
import ReadToCloudFirestore from '@/components/cloudFirestore/Read.js';
import Toolbars from '../components/subpages/toolbar'

firebase();

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NPCA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbars />
      <main className={styles.main}>

        <div className={styles.spacing}></div>
        <div className={styles.center}>
          <Image
            src="/npca.png"
            alt="Next.js Logo"
            width={380}
            height={167}
            priority
          />
          <div className={styles.thirteen}>
            Novel
            Prediction
            Computational
            Analysis
          </div>
        </div>
        <div> TeleHealth, ran by data.</div>

        <div className={styles.spacing}></div>
        <div className={styles.spacing}></div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Log In <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Forms and Calls <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Patient Profiles <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Privacy and HIPAA Policies <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              NPCA will not be liable for any misuse of data. Please familiarize yourself with your state laws and the Ferderal HIPAA regulations and obtain patient consent before using our services.
            </p>
          </a>
        </div>

        <div className={styles.spacing}></div>
        <div className={styles.spacing}></div>
        <WriteToCloudFirestore />
        <ReadToCloudFirestore />
      </main>
    </>
  );
}
